### ISSUE TITLE
Support for async log/metric forwarding (DD_FLUSH_TO_LOG)?

### ISSUE THREAD

**Issue by inakianduaga** [DataDog/datadog-lambda-java#10]
The Node.js lambda has support for shipping logs asynchroneously via the `DD_FLUSH_TO_LOG` parameter, and that's the preferred way to ship log/metrics. To unify the node/java setups, it would be great to have this option available for JAVA lambdas as well.

**Comment by agocs** [comment]
You are correct in that asynch log shipping is the preferred behavior. `DD_FLUSH_TO_LOG` was not included in this library because this library's behavior is the same as `DD_FLUSH_TO_LOG=true`
