### ISSUE TITLE
Java 8 not supported

### ISSUE THREAD

**Issue by malbanesi-ascii** [DataDog/datadog-lambda-java#13]
Java 8 is not supported on release 0.0.3

> Information:javac 1.8.0_181 was used to compile java sources

> Error:(13, 41) java: cannot access com.datadoghq.datadog_lambda_java.DDLambda
>  bad class file: /Users/user/.m2/repository/com/datadoghq/datadog-lambda-java/0.0.3/datadog-lambda-java-0.0.3.jar!/com/datadoghq/datadog_lambda_java/DDLambda.class
>    class file has wrong version 55.0, should be 52.0
>    Please remove or make sure it appears in the correct subdirectory of the classpath.

Version 55 corresponds to Java 11

**Comment by agocs** [comment]
Good catch. I'll fix this right away.

**Comment by agocs** [comment]
@malbanesi-ascii Okay, I've published 0.0.4 on jFrog Bintray. I downloaded the jar file to verify that it's compiled for version 52. Sorry about the inconvenience!
