### ISSUE TITLE
How to use this library with Spring cloud functions and aws serverless containers

### ISSUE THREAD

**Issue by swagsb** [DataDog/datadog-lambda-java#16]
Hi,

The example given in the library documentation is of a simple lambda with core java . However we have few lambdas created out of Spring cloud functions and AWS serverless containers . 
Please see information on the same [here](https://github.com/awslabs/aws-serverless-java-container).

These lambda handlers have single line code to proxy the request response.   And for spring cloud functions, lambda handlers are given by spring .  In such cases , how can the library be used to capture metrics and traces ?

**Comment by agocs** [comment]
Hi @swagsb,
Looking at the sample code, this should work fundamentally:

```
public class StreamLambdaHandler implements RequestStreamHandler {
    private static SpringLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    static {
        try {
            handler = SpringLambdaContainerHandler.getAwsProxyHandler(PetStoreSpringAppConfig.class);
        } catch (ContainerInitializationException e) {
            // if we fail here. We re-throw the exception to force another cold start
            e.printStackTrace();
            throw new RuntimeException("Could not initialize Spring framework", e);
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
       DDLambda dd = new DDLambda(context);  //Records enhanced execution metrics
       handler.proxyStream(inputStream, outputStream, context);
    }
}
```

You could then construct a singleton class to hold `DDLambda dd`, and then retrieve a reference to `dd` from within your Spring application whenever you need it.

I haven't confirmed support for extracting X-Ray trace headers from an `InputStream`, so you might have difficulty instrumenting any REST requests that might be made from within your Spring app. If that's a priority for you, let me know and I can add a feature request.
