### ISSUE TITLE
Tracing Lambda code

### ISSUE THREAD

**Issue by swagsb** [DataDog/datadog-lambda-java#17]
If we am not interested in distributed tracing but simply tracing the lambda code , how to collect traces in such case.  ie When the request is received to lambda entrypoint , simply to capture traces of the code executed line by line and not to outgoing requests etc for which the request wrappers are given I presume.

**Comment by DarcyRaynerDD** [comment]
Hi @swagsb, we will be working on bringing dd-trace-java support to this layer in the future. Right now, we support [X-Ray traces in datadog](https://docs.datadoghq.com/integrations/amazon_xray/?tab=gorubyjavanet).

**Comment by agocs** [comment]
Full-fledged tracing is now supported using the `dd-java-agent`, detailed here: https://github.com/DataDog/datadog-lambda-java#distributed-tracing
