### ISSUE TITLE
Provide option to enable APM Tracing w/out X-Ray

### ISSUE THREAD

**Issue by jwilmoth-nc** [DataDog/datadog-lambda-java#22]
The current library requires X-Ray to be enabled in order to receive APM traces (https://docs.datadoghq.com/serverless/installation/java/?tab=maven#configure-the-function). 
 Other DD lambda tracing libs (e.g. https://docs.datadoghq.com/serverless/installation/nodejs/?tab=custom) don't require X-Ray as a dependency.  It would be nice to have the option of enabling traces w/out this additional $/dependency.

**Comment by agocs** [comment]
You may now trace your lambda function execution and include it as part of a distributed trace by installing the `dd-java-agent` Lambda layer as detailed here: https://github.com/DataDog/datadog-lambda-java#distributed-tracing
