### ISSUE TITLE
Requires lambdas to include multiple http client dependencies

### ISSUE THREAD

**Issue by jwilmoth-nc** [DataDog/datadog-lambda-java#23]
Because there's only one datadog-lambda-java artifact and the library supports 3 different http clients at the moment, lambda functions have to include both of the non-native Java dependencies even if they only use one (or none if the java.net.HttpUrlConnection is the function's http client).  Using a service provider model and providing different artifacts for the different implementations would allow DD customers to optimize their function jars.

**Comment by tianchu** [comment]
datadog-lambda-java will soon be no longer required to instrument Lambda functions using the Datadog Lambda extension. Therefore we have no plan to make this improvement.
