### ISSUE TITLE
Enhanced metrics not send with custom tags

### ISSUE THREAD

**Issue by grzegorznittner** [DataDog/datadog-lambda-java#33]
By enhanced metrics I mean those generated with prefix aws.lambda.enhanced.

For custom metrics, we can pass an array of tags which is then reflected in generated logs and in the Datadog interface.
However, enhanced logs that are generated automatically by the DDLambda class get tags autogenerated only. I cannot pass my own list of tags, as a result, enhanced metrics are not very usable in Datadog.

Please add a way to specify tags that are added to the autogenerated tags for enhanced metrics.

**Comment by tianchu** [comment]
@grzegorznittner you request makes sense. One potential workaround is adding the tags to your Lambda function itself, and they will automatically apply to all the metrics (including enhanced metrics), logs, and traces emitted from this Lambda function, but this won't work if you need to add custom tags dynamically in the function code.

**Comment by grzegorznittner** [comment]
@tianchu Reading tags from the lambda function seems quite a good idea, I wouldn't even call it a workaround. Looking at the code, this still has to be implemented.

**Comment by tianchu** [comment]
@grzegorznittner that's done by the Forwarder (adding the tags when forwarding the metrics from logs), just ensure you are using the latest version of the forwarder and [DdFetchLambdaTags](https://github.com/DataDog/datadog-serverless-functions/blob/8883382e2ce77361bb7fc35e9d336c376db0aec6/aws/logs_monitoring/template.yaml#L59) is set to `true`.
