### ISSUE TITLE
Library missing from JFrog Bintray? 

### ISSUE THREAD

**Issue by darrenoc3** [DataDog/datadog-lambda-java#44]
For the last while, we have been seeing the following:
```
  > Could not resolve com.datadoghq:datadog-lambda-java:0.0.4.
         > Could not get resource 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/datadog-lambda-java/0.0.4/datadog-lambda-java-0.0.4.pom'.
            > Could not GET 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/datadog-lambda-java/0.0.4/datadog-lambda-java-0.0.4.pom'. Received status code 403 from server: Forbidden
```

Have Datadog libs been removed? I notice that https://bintray.com/datadog/datadog-maven 404's

**Comment by agocs** [comment]
Hey @darrenoc3, JFrog chose to sunset Bintray in early May. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We're on MavenCentral now! https://search.maven.org/artifact/com.datadoghq/datadog-lambda-java

Let me know if you're still seeing Bintray in our docs so I can change that. The docs should all point to MavenCentral.

**Comment by darrenoc3** [comment]
Thanks for the swift response Christopher. We weren't up to date. I'll point our jobs to MavenCentral instead, thanks again.

**Comment by agocs** [comment]
No worries! Have a good evening
