### ISSUE TITLE
Micrometer support

### ISSUE THREAD

**Issue by tom-mi** [DataDog/datadog-lambda-java#45]
Hello,

(not sure if this is the right place or if that's rather a topic for the micrometer maintainers)
We are using the datadog-lambda-java to send custom metrics from a lambda function implemented with spring-cloud-function. Therefore we have already micrometer as a common metrics facade in place.
We tried to use the [direct datadog api approach](https://micrometer.io/docs/registry/datadog#_direct_to_datadog_api_approach), however that registry does not work properly within a lambda, as it does not flush the metrics at the end of the invocation and it gets confused when a (warm) lambda function is re-activated for the next call.

Would it be possible to provide a micrometer integration that works within AWS Lambda?

**Comment by agocs** [comment]
Hi @tom-mi ,
This is mildly complicated. Datadog-lambda-java handles metrics by writing them to the Lambda function's Cloudwatch log stream. The metrics are then picked up by the Datadog Forwarder lambda function, converted into metrics, and sent to Datadog's metrics backend. There are a couple things we could try here:

1. Create a new Micrometer registry that flushes metrics to logs in the format the Datadog forwarder expects
1. Modify the existing Micrometer registry to flush metrics to the API immediately (this is one of the supported behaviors of Datadog-lambda-js and -py. It doesn't add a lot of overhead to the Lambda invocation, especially if flushing is accomplished in a separate thread)
1. Wait for the [Datadog Lambda Extension](https://www.datadoghq.com/blog/datadog-lambda-extension/) to support Java Lambda functions. The Lambda extension has a modified version of dogstatsd built in, and that will support the [dogstatsd approach](https://micrometer.io/docs/registry/datadog#_through_dogstatsd_approach) documented in the Micrometer docs.

I'll create a feature request. I think option 3 is already on the roadmap, but I'll have to check with the PM on the Lambda Extension project. In the mean time, I'll investigate how much effort would be required to add an immediate flushing option to the existing Micrometer registry.

**Comment by tianchu** [comment]
Closing this since our Lambda Extension already support sending custom metrics for Java.
