### ISSUE TITLE
No Interface for S3Event, Context Java Handler

### ISSUE THREAD

**Issue by fazil1der** [DataDog/datadog-lambda-java#52]
com.datadoghq.datadog_lambda_java.DDLambda Has No constructer for S3Eevent.

**Comment by agocs** [comment]
Hi @fazil1der, thanks for opening this issue. What behavior would you like to see if you initialize `new DDLambda(S3Event, context)`?

Unfortunately, I don't think there's an easy way to trace across S3 events, so it doesn't make a lot of sense to try to extract trace context from one. If you're inserting trace context into an S3 object, you might want to implement a custom Headerable (similar to KinesisHeaderable or SQSHeaderable).

**Comment by fazil1der** [comment]
Hi @agocs 

Thanks. Currently exploring the approach using new DDLambda(context).
