### ISSUE TITLE
Tags are formatted wrong for the custom metric

### ISSUE THREAD

**Issue by VitoMakarevich** [DataDog/datadog-lambda-java#75]
Here I created an issue and investigated it. https://github.com/DataDog/datadog-lambda-extension/issues/57
In short, this code is incorrect https://github.com/DataDog/datadog-lambda-java/blob/main/src/main/java/com/datadoghq/datadog_lambda_java/MetricWriter.java#L64 
The repl example is https://replit.com/@VitaliyMakarevi/PepperyAgileMatrix#Main.java
So as you could see, the logs are concatenated without commas using StringBuilder, could someone create a patch & make a new release with the fix?

**Comment by IvanTopolcic** [comment]
Fixed in [v1.4.4](https://github.com/DataDog/datadog-lambda-java/releases/tag/1.4.4). Thanks so much for your contribution, we really appreciate it!
