### ISSUE TITLE
slf4j dependency contains vulnerabilities

### ISSUE THREAD

**Issue by dangothemango** [DataDog/datadog-lambda-java#82]
https://github.com/DataDog/datadog-lambda-java/blob/4859b16c5b6de0838c40340f35c0b681bc4b8f83/build.gradle#L33

This dependency contains a transitive dependency on log4j 1.2.17 which contains severe vulnerabilities.

https://mvnrepository.com/artifact/org.slf4j/slf4j-log4j12/1.7.32

**Comment by CNorskov** [comment]
When can we expect a new release with this dependency removed?

**Comment by CNorskov** [comment]
When can we expect a new release with this dependency removed?
