### ISSUE TITLE
Periodical errors - Unable to create StatsD client / Unable to bind to an available socket / too many open files & error creating socket

### ISSUE THREAD

**Issue by drobakowski** [DataDog/datadog-lambda-java#84]
Hi @maxday,

after switching to the new Datadog Extension v22 with the release of [serverless-plugin-datadog v5.0.1](https://github.com/DataDog/serverless-plugin-datadog/compare/v5.0.0...v5.0.1) we do see errors again (Unable to create StatsD client / Unable to bind to an available socket / too many open files & error creating socket), some of them we've seen first time with https://github.com/DataDog/datadog-lambda-java/issues/78:

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/81381/169327259-2a5d9ae7-9271-4f82-b942-a812dd621e7f.png">

as well as the following:

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/81381/169327503-e2d9bfca-7598-4a61-ba61-87a21ab10472.png">

`DD_RUNTIME_METRICS_ENABLED: false` is still set.

Do you maybe have any idea what we're doing wrong or what have changed?

Thanks and all the best
David

**Comment by agocs** [comment]
Hi @drobakowski , this might be related to #74 and might be fixed by #85 . I've released datadog-lambda-java v1.4.5 with that fix included. Let me know if you get a chance to test this out.
-Chris
