### ISSUE TITLE
Distributed tracing with Unirest HTTP library

### ISSUE THREAD

**Issue by sujee81** [DataDog/datadog-lambda-java#9]
I use Unirest HTTP library in my Java lambda to call backend APIs. In order to trace the calls end to end, it would be great, if Unirest is supported by this library. Thank you.

**Comment by DarcyRaynerDD** [comment]
@sujee81 We are still working on bringing dd-trace-java support to the lambda runtime. However looking at our [compatibility support](https://docs.datadoghq.com/tracing/compatibility_requirements/java/), we don't have a Unirest integration yet. It might be a better idea to post that feature request on the [dd-trace-java](https://github.com/DataDog/dd-trace-java/issues) repo.

**Comment by sujee81** [comment]
Sure. Thanks @DarcyRaynerDD
